version: '3.7'

services:
  widgethubbackend:
    image: widgethubbackend
    ports:
      - 8080:8080
  expressbackend:
    image: express-app
    ports:
      - 3000:3000
  db:
    image: "postgres" 
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/data
    ports:
      - 5432:5432
  
volumes:
  db-data:
